### ISSUE TITLE
for hg38 dataset

### ISSUE THREAD

**Issue by parida007** [bioinf/SICER2#1]
how to find peaks for hg38/ add in the species.py

**Comment by latur** [comment]
The [species.py](https://github.com/bioinf/SICER2/blob/master/src/species.py) file contains the sizes of the largest chromosomes to automatically determine the type of organism. I [added](https://github.com/bioinf/SICER2/commit/d970f444aeee4c0787e481f999da00c4e55b84a8
) [hg38](https://genome.ucsc.edu/goldenPath/help/hg38.chrom.sizes), please download the latest version of SICER2 and check it out.
